### ISSUE TITLE
Build error - Cannot find module 'asar/node_modules/chromium-pickle-js'

### ISSUE THREAD

**Issue by scowalt** [dustinblackman/Championify#158]
Hey Dustin,

I get the following error whenever I `npm install` to try to build Championify. This is on Windows 10. Any insight as to what may be causing this?

Thanks!

```
D:\Code\Championify>npm install
module.js:341
    throw err;
    ^

Error: Cannot find module 'asar/node_modules/chromium-pickle-js'
  at Function.Module._resolveFilename (module.js:339:15)
  at Function.Module._load (module.js:290:25)
  at Module.require (module.js:367:17)
  at require (internal/module.js:16:19)
  at Object.<anonymous> (D:\Code\Championify\node_modules\gulp-asar\index.js:7:14)
  at Module._compile (module.js:413:34)
  at Object.Module._extensions..js (module.js:422:10)
  at Module.load (D:\Code\Championify\node_modules\coffee-script\lib\coffee-script\register.js:45:36)
  at Function.Module._load (module.js:314:12)
  at Module.require (module.js:367:17)
  at require (internal/module.js:16:19)
  at Object.<anonymous> (D:\Code\Championify\tasks\compile.coffee:2:8)
  at Object.<anonymous> (D:\Code\Championify\tasks\compile.coffee:1:1)
  at Module._compile (module.js:413:34)
  at Object.loadFile (D:\Code\Championify\node_modules\coffee-script\lib\coffee-script\register.js:16:19)
  at Module.load (D:\Code\Championify\node_modules\coffee-script\lib\coffee-script\register.js:45:36)
  at Function.Module._load (module.js:314:12)
  at Module.require (module.js:367:17)
  at require (internal/module.js:16:19)
  at requireDir (D:\Code\Championify\node_modules\require-dir\index.js:116:33)
  at Object.<anonymous> (D:\Code\Championify\gulpfile.coffee:6:1)
  at Object.<anonymous> (D:\Code\Championify\gulpfile.coffee:1:1)
  at Module._compile (module.js:413:34)
  at Object.loadFile (D:\Code\Championify\node_modules\coffee-script\lib\coffee-script\register.js:16:19)
  at Module.load (D:\Code\Championify\node_modules\coffee-script\lib\coffee-script\register.js:45:36)
  at Function.Module._load (module.js:314:12)
  at Module.require (module.js:367:17)
  at require (internal/module.js:16:19)
  at Liftoff.handleArguments (D:\Code\Championify\node_modules\gulp\bin\gulp.js:116:3)
  at Liftoff.<anonymous> (D:\Code\Championify\node_modules\liftoff\index.js:192:16)
  at module.exports (D:\Code\Championify\node_modules\flagged-respawn\index.js:17:3)
  at Liftoff.<anonymous> (D:\Code\Championify\node_modules\liftoff\index.js:185:9)
  at D:\Code\Championify\node_modules\liftoff\index.js:159:9
  at D:\Code\Championify\node_modules\v8flags\index.js:108:14
  at D:\Code\Championify\node_modules\v8flags\index.js:36:12
  at D:\Code\Championify\node_modules\v8flags\index.js:47:7
  at _combinedTickCallback (node.js:376:9)
  at process._tickCallback (node.js:407:11)
  at Function.Module.runMain (module.js:449:11)
  at startup (node.js:142:18)
  at node.js:939:3
```

**Comment by dustinblackman** [comment]
Using Node 4 and npm 2?

**Comment by scowalt** [comment]
After switching to node v4.4.0 **and** deleting the existing `node_modules` folder, I was able to build. Thanks! Guess I missed that in the README.

For anyone coming across this in the future, I recommend using [nvm-windows](https://github.com/coreybutler/nvm-windows) to switch between node versions.
