### ISSUE TITLE
Can't get LoL version

### ISSUE THREAD

**Issue by riiferreira10** [dustinblackman/Championify#230]
Well, I tried to update to the patch 6.24 after 2 weeks without playing but when I open the program don't allow to Import builds, it shows:

LoL Version: Loading.... 

I tried to reinstall, clean the folder from AppData but nothing works.

**Comment by malsf21** [comment]
Hey @riiferreira10, I'm not the dev but have you deleted the Local and Roaming folders, and re-installed? It's worked for me after doing that. I had the same problem that you did.

**Comment by riiferreira10** [comment]
2016-12-20T23:49:03.537Z - info: Version: 1.3.8
2016-12-20T23:49:09.669Z - warn:  RequestError: Can't get Riot Version
    at C:\Program Files (x86)\Championify\resources\app.asar\js\championify.js:88:11
    at tryCatcher (C:\Program Files (x86)\Championify\resources\app.asar\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Program Files (x86)\Championify\resources\app.asar\node_modules\bluebird\js\release\promise.js:503:31)
    at Promise._settlePromise (C:\Program Files (x86)\Championify\resources\app.asar\node_modules\bluebird\js\release\promise.js:560:18)
    at Promise._settlePromise0 (C:\Program Files (x86)\Championify\resources\app.asar\node_modules\bluebird\js\release\promise.js:605:10)
    at Promise._settlePromises (C:\Program Files (x86)\Championify\resources\app.asar\node_modules\bluebird\js\release\promise.js:680:18)
    at Async._drainQueue (C:\Program Files (x86)\Championify\resources\app.asar\node_modules\bluebird\js\release\async.js:126:16)
    at Async._drainQueues (C:\Program Files (x86)\Championify\resources\app.asar\node_modules\bluebird\js\release\async.js:136:10)
    at Async.drainQueues (C:\Program Files (x86)\Championify\resources\app.asar\node_modules\bluebird\js\release\async.js:16:14)
    at MutationObserver.<anonymous> (C:\Program Files (x86)\Championify\resources\app.asar\node_modules\bluebird\js\release\schedule.js:37:13)
    at process._tickCallback (node.js:369:9)
Cause: Error: certificate has expired
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1000:38)
    at emitNone (events.js:67:13)
    at TLSSocket.emit (events.js:166:7)
    at TLSSocket._finishInit (_tls_wrap.js:567:8)

**Comment by riiferreira10** [comment]
IT WORKED, THANK YOU!
MERRY CHRISTMAS OHOHOHOH! 👍

**Comment by malsf21** [comment]
No problem! @dustinblackman I asked a friend to test this solution, and it works as well. For now, a re-install and wiping both AppData folders ends up working properly.

**Comment by dustinblackman** [comment]
Dup.  https://github.com/dustinblackman/Championify/issues/227
