### ISSUE TITLE
After updating to 2.0.0 (reinstall), I am getting error saying Error: ETIMEDOUT or ESOCKETTIMEDOUT

### ISSUE THREAD

**Issue by foodtooth** [dustinblackman/Championify#237]
The error comes out when items are being downloaded, or even when I was in the main frame doing nothing.

- I'm sure championify is opened with administrator
- the program has been allowed to pass the firewall

Here is example of the error log while the downloading was in progress:

`error:  Error: ESOCKETTIMEDOUT
    at ClientRequest.<anonymous> (C:\Users\micha\AppData\Local\Championify\app-2.0.0\resources\app.asar\node_modules\request\request.js:779:19)
    at ClientRequest.g (events.js:286:16)
    at emitNone (events.js:86:13)
    at ClientRequest.emit (events.js:185:7)
    at Socket.emitTimeout (_http_client.js:614:10)
    at Socket.g (events.js:286:16)
    at emitNone (events.js:86:13)
    at Socket.emit (events.js:185:7)
    at Socket._onTimeout (net.js:334:8)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)`

Anyone can help me?

**Comment by dustinblackman** [comment]
Something on your system or network is blocking. Can you post your full log please?

**Comment by T9090** [comment]
maybe i have the same problem . 


2016-12-22T19:09:20.023Z - warn:  ExternalError: Probuilds failed to parse KDA for vladimir
    at then.map.then.then.then.catch.err (C:\Users\Utente\AppData\Local\Championify\app-2.0.0\resources\app.asar\js\sources\probuilds.js:85:11)
    at tryCatcher (C:\Users\Utente\AppData\Local\Championify\app-2.0.0\resources\app.asar\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Utente\AppData\Local\Championify\app-2.0.0\resources\app.asar\node_modules\bluebird\js\release\promise.js:510:31)
    at Promise._settlePromise (C:\Users\Utente\AppData\Local\Championify\app-2.0.0\resources\app.asar\node_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (C:\Users\Utente\AppData\Local\Championify\app-2.0.0\resources\app.asar\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (C:\Users\Utente\AppData\Local\Championify\app-2.0.0\resources\app.asar\node_modules\bluebird\js\release\promise.js:687:18)
    at Async._drainQueue (C:\Users\Utente\AppData\Local\Championify\app-2.0.0\resources\app.asar\node_modules\bluebird\js\release\async.js:138:16)
    at Async._drainQueues (C:\Users\Utente\AppData\Local\Championify\app-2.0.0\resources\app.asar\node_modules\bluebird\js\release\async.js:148:10)
    at Async.drainQueues (C:\Users\Utente\AppData\Local\Championify\app-2.0.0\resources\app.asar\node_modules\bluebird\js\release\async.js:17:14)
    at process._tickCallback (internal/process/next_tick.js:103:7)
Cause: Error: connect ECONNREFUSED 151.101.192.249:80
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1081:14)
2016-12-22T19:09:20.024Z - error:  Error: connect ECONNREFUSED 151.101.192.249:80
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1081:14)
2016-12-22T19:09:20.054Z - warn:  Error: connect ECONNREFUSED 104.27.163.170:80
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1081:14)
2016-12-22T19:09:20.056Z - info: Elaborazione Champion.gg: Camille
2016-12-22T19:09:20.138Z - warn:  Error: connect ECONNREFUSED 143.95.250.70:80
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1081:14)
2016-12-22T19:09:20.138Z - info: Elaborazione Lolflavor ARAM: Thresh
2016-12-22T19:09:20.147Z - warn:  Error: connect ECONNREFUSED 143.95.250.70:80
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1081:14)
2016-12-22T19:09:20.148Z - info: Elaborazione Lolflavor ARAM: Teemo
2016-12-22T19:09:20.194Z - warn:  ExternalError: Probuilds failed to parse KDA for warwick
    at then.map.then.then.then.catch.err (C:\Users\Utente\AppData\Local\Championify\app-2.0.0\resources\app.asar\js\sources\probuilds.js:85:11)
    at tryCatcher (C:\Users\Utente\AppData\Local\Championify\app-2.0.0\resources\app.asar\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Utente\AppData\Local\Championify\app-2.0.0\resources\app.asar\node_modules\bluebird\js\release\promise.js:510:31)
    at Promise._settlePromise (C:\Users\Utente\AppData\Local\Championify\app-2.0.0\resources\app.asar\node_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (C:\Users\Utente\AppData\Local\Championify\app-2.0.0\resources\app.asar\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (C:\Users\Utente\AppData\Local\Championify\app-2.0.0\resources\app.asar\node_modules\bluebird\js\release\promise.js:687:18)
    at Async._drainQueue (C:\Users\Utente\AppData\Local\Championify\app-2.0.0\resources\app.asar\node_modules\bluebird\js\release\async.js:138:16)
    at Async._drainQueues (C:\Users\Utente\AppData\Local\Championify\app-2.0.0\resources\app.asar\node_modules\bluebird\js\release\async.js:148:10)
    at Async.drainQueues (C:\Users\Utente\AppData\Local\Championify\app-2.0.0\resources\app.asar\node_modules\bluebird\js\release\async.js:17:14)
    at process._tickCallback (internal/process/next_tick.js:103:7)
Cause: Error: connect ECONNREFUSED 151.101.192.249:80
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1081:14)
2016-12-22T19:09:20.227Z - warn:  Error: connect ECONNREFUSED 143.95.250.70:80
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1081:14)
2016-12-22T19:09:20.227Z - info: Elaborazione Lolflavor ARAM: Taric
2016-12-22T19:09:20.888Z - info: Elaborazione Champion.gg: Cassiopeia
2016-12-22T19:09:21.683Z - warn:  ExternalError: Probuilds failed to parse KDA for viktor
    at then.map.then.then.then.catch.err (C:\Users\Utente\AppData\Local\Championify\app-2.0.0\resources\app.asar\js\sources\probuilds.js:85:11)
    at tryCatcher (C:\Users\Utente\AppData\Local\Championify\app-2.0.0\resources\app.asar\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Utente\AppData\Local\Championify\app-2.0.0\resources\app.asar\node_modules\bluebird\js\release\promise.js:510:31)
    at Promise._settlePromise (C:\Users\Utente\AppData\Local\Championify\app-2.0.0\resources\app.asar\node_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (C:\Users\Utente\AppData\Local\Championify\app-2.0.0\resources\app.asar\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (C:\Users\Utente\AppData\Local\Championify\app-2.0.0\resources\app.asar\node_modules\bluebird\js\release\promise.js:687:18)
    at Async._drainQueue (C:\Users\Utente\AppData\Local\Championify\app-2.0.0\resources\app.asar\node_modules\bluebird\js\release\async.js:138:16)
    at Async._drainQueues (C:\Users\Utente\AppData\Local\Championify\app-2.0.0\resources\app.asar\node_modules\bluebird\js\release\async.js:148:10)
    at Async.drainQueues (C:\Users\Utente\AppData\Local\Championify\app-2.0.0\resources\app.asar\node_modules\bluebird\js\release\async.js:17:14)
    at process._tickCallback (internal/process/next_tick.js:103:7)
Cause: Error: connect ECONNREFUSED 151.101.12.249:80
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1081:14)
2016-12-22T19:09:22.079Z - info: Elaborazione Lolflavor ARAM: Talon ....

the programm arrive at 20 % and next stop

**Comment by foodtooth** [comment]
- I'm not sure which exe I should put into the firewall's whitelist, so I added both (one in Championify, and another in Championify/app-2.0.0)
- Here is the full log

> 2016-12-23T02:06:59.160Z - info: Version: 2.0.0
> 2016-12-23T02:07:00.379Z - info: Checking for updates
> 2016-12-23T02:07:01.861Z - info: No updates found
> 2016-12-23T02:07:24.094Z - info: Locale: en
> 2016-12-23T02:07:24.105Z - info: Saved preference file to C:\Users\alphabing\AppData\Roaming\Championify\prefs.json
> 2016-12-23T02:07:24.113Z - info: Getting LoL Version
> 2016-12-23T02:07:24.830Z - info: Downloading Champs from Riot
> 2016-12-23T02:07:26.340Z - info: Downloading ARAM Champs
> 2016-12-23T02:07:26.354Z - info: Processing Champion.gg: Zyra
> 2016-12-23T02:07:26.357Z - info: Processing Champion.gg: Zilean
> ...
> 2016-12-23T02:08:44.235Z - info: Processing Champion.gg: Wukong
> 2016-12-23T02:08:45.218Z - info: Processing Lolmasters: Maokai
> 2016-12-23T02:08:45.472Z - error:  Error: ESOCKETTIMEDOUT
>     at ClientRequest.<anonymous> (C:\Users\alphabing\AppData\Local\Championify\app-2.0.0\resources\app.asar\node_modules\request\request.js:779:19)
>     at ClientRequest.g (events.js:286:16)
>     at emitNone (events.js:86:13)
>     at ClientRequest.emit (events.js:185:7)
>     at Socket.emitTimeout (_http_client.js:614:10)
>     at Socket.g (events.js:286:16)
>     at emitNone (events.js:86:13)
>     at Socket.emit (events.js:185:7)
>     at Socket._onTimeout (net.js:334:8)
>     at tryOnTimeout (timers.js:232:11)
>     at Timer.listOnTimeout (timers.js:202:5)
> 2016-12-23T02:08:45.700Z - info: Processing ProBuilds: Kennen
> 2016-12-23T02:08:46.080Z - info: Processing Champion.gg: Mordekaiser
> ...
> 2016-12-23T02:10:14.857Z - info: Processing Koreanbuilds: Malphite
> 2016-12-23T02:10:18.088Z - info: Processing Koreanbuilds: Malzahar

**Comment by dustinblackman** [comment]
@foodtooth @T9090 I have a theory. If you were to select one source at a time and import each individually, would they all import successfully?

**Comment by foodtooth** [comment]
@dustinblackman Thanks for your reply, it works!

I tried to select source one by one and check "Download ARAM item sets" to download two sources at a time and it works. (Only failed with the same error when I selected probuilds, but it worked when I tried again.)

So I tried again with all of the sources without probuilds, but still failed with the same error.

**Comment by dustinblackman** [comment]
I have a feeling something on your systems has something setting a max connections per application. When using multiple sources, there's a large number of requests being made at the same time. I'll add queuing to limit the number of requests being made in hopes to solve this.

**Comment by foodtooth** [comment]
@dustinblackman Sure, I would love to help.

**Comment by Brelvor** [comment]
@dustinblackman just sent the build , i would gladly help.

**Comment by ninjay997** [comment]
I got same error on app but I think it was different in log, probuilds failed to send data for garen so I had to remove probuilds for it to work

**Comment by dustinblackman** [comment]
@foodtooth @Brelvor @ninjay997 Sorry for the delay guys. Here's a test build that has Championify limited to making 10 requests at time. Try adding all the sources, and let me know if you end up with connection errors. If not, I'll add it to my next release. Thanks again for helping with testing. http://www62.zippyshare.com/v/XTo5dGky/file.html

**Comment by NelsonMinar** [comment]
FWIW I'm seeing this error myself on my Mac running v2.0.1. But only if I include op.gg as a source. It doesn't matter how many/few other sources I have. It's worked in the past, but not today, and I am wondering if perhaps op.gg is down. Anyway it's a different issue than you're chasing with the 10 requests limit. My main feedback here is to make the error reporting a little better, like showing which source gave the error. The logfile is misleading; a naive user would look at this report below and blame champion.gg

```
2017-01-18T21:16:43.574Z - info: Processing Champion.gg: Zac
2017-01-18T21:16:43.775Z - info: Processing Champion.gg: Zed
2017-01-18T21:16:55.051Z - error:  Error: ESOCKETTIMEDOUT
    at ClientRequest.<anonymous> (/Applications/Championify.app/Contents/Resources/app.asar/node_modules/request/request.js:779:19)
    at ClientRequest.g (events.js:286:16)
    at emitNone (events.js:86:13)
    at ClientRequest.emit (events.js:185:7)
    at Socket.emitTimeout (_http_client.js:614:10)
    at Socket.g (events.js:286:16)
    at emitNone (events.js:86:13)
    at Socket.emit (events.js:185:7)
    at Socket._onTimeout (net.js:334:8)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
```

**Comment by dustinblackman** [comment]
@NelsonMinar Fair point, that should have better error handling. I'll include it with the queue fix. Thanks.

**Comment by johnsaucier** [comment]
I am also now seeing this error, I played last night without any issue, something has changed, I am doing nothing different.

**Comment by Nefari0uss** [comment]
I'm getting this error but I suspect it was due to op.gg stuck on `Loading...`. Removing `op.gg` from the sources used fixed it for me. Can give screenshot/log if needed. 

Win 10 x64, v2.0.1

**Comment by johnsaucier** [comment]
You sir are correct, removing that made it finish. Is there anyway to check them before trying to download each one, and skip if they fail the check? But continue with those that do not?

**Comment by doubledgedboard** [comment]
Getting this now, too. Looks like bad error handling \ retry logic for when one of the pool's connections times out.

**Comment by foodtooth** [comment]
I'm sorry that I had no chance to checkout github during Chinese New Year and failed to run the test build. Thanks for the new release!
