### ISSUE TITLE
Error .json failed to write

### ISSUE THREAD

**Issue by bloodygun** [dustinblackman/Championify#256]
2017-01-15T11:26:44.993Z - info: Version: 2.0.1
2017-01-15T11:26:46.340Z - info: Checking for updates
2017-01-15T11:26:46.696Z - info: No updates found
2017-01-15T11:26:46.744Z - info: Locale: it
2017-01-15T11:26:46.752Z - info: Saved preference file to C:\Users\Simone\AppData\Roaming\Championify\prefs.json
2017-01-15T11:26:46.754Z - info: Sto ottenendo la versione di LoL
2017-01-15T11:26:47.115Z - info: Download dei campioni dalla Riot in corso
2017-01-15T11:26:48.237Z - info: Elaborazione Champion.gg: Zyra
2017-01-15T11:26:48.240Z - info: Elaborazione Champion.gg: Zilean
2017-01-15T11:26:48.242Z - info: Elaborazione Champion.gg: Ziggs
2017-01-15T11:26:48.243Z - info: Elaborazione Lolmasters: Aatrox
2017-01-15T11:26:48.245Z - info: Elaborazione Lolmasters: Ahri
2017-01-15T11:26:49.140Z - info: Elaborazione Champion.gg: Aatrox
2017-01-15T11:26:49.319Z - info: Elaborazione Lolmasters: Zyra
2017-01-15T11:26:49.401Z - info: Elaborazione Lolmasters: Zilean
2017-01-15T11:26:49.569Z - info: Elaborazione Lolmasters: Ziggs
2017-01-15T11:26:49.665Z - info: Elaborazione Lolmasters: Zed
2017-01-15T11:26:49.818Z - info: Elaborazione Champion.gg: Ahri
2017-01-15T11:26:49.847Z - info: Elaborazione Lolmasters: Zac
2017-01-15T11:26:49.874Z - info: Elaborazione Champion.gg: Akali
2017-01-15T11:26:49.992Z - info: Elaborazione Lolmasters: Yorick
2017-01-15T11:26:50.065Z - info: Elaborazione Lolmasters: Yasuo
2017-01-15T11:26:50.305Z - info: Elaborazione Lolmasters: Xin Zhao
2017-01-15T11:26:50.564Z - info: Elaborazione Lolmasters: Xerath
2017-01-15T11:26:50.589Z - info: Elaborazione Champion.gg: Alistar
2017-01-15T11:26:50.619Z - info: Elaborazione Champion.gg: Amumu
2017-01-15T11:26:50.746Z - info: Elaborazione Lolmasters: Warwick
2017-01-15T11:26:51.024Z - info: Elaborazione Lolmasters: Volibear
2017-01-15T11:26:51.283Z - info: Elaborazione Champion.gg: Anivia
2017-01-15T11:26:51.306Z - info: Elaborazione Lolmasters: Vladimir
2017-01-15T11:26:51.372Z - info: Elaborazione Champion.gg: Annie
2017-01-15T11:26:51.376Z - info: Elaborazione Lolmasters: Viktor
2017-01-15T11:26:51.416Z - info: Elaborazione Champion.gg: Ashe
2017-01-15T11:26:51.501Z - info: Elaborazione Lolmasters: Vi
2017-01-15T11:26:51.560Z - info: Elaborazione Lolmasters: Vel'Koz
2017-01-15T11:26:51.747Z - info: Elaborazione Lolmasters: Veigar
2017-01-15T11:26:51.831Z - info: Elaborazione Lolmasters: Vayne
2017-01-15T11:26:52.044Z - info: Elaborazione Lolmasters: Varus
2017-01-15T11:26:52.135Z - info: Elaborazione Lolmasters: Urgot
2017-01-15T11:26:52.172Z - info: Elaborazione Champion.gg: Aurelion Sol
2017-01-15T11:26:52.275Z - info: Elaborazione Champion.gg: Azir
2017-01-15T11:26:52.286Z - info: Elaborazione Lolmasters: Udyr
2017-01-15T11:26:52.367Z - info: Elaborazione Lolmasters: Twitch
2017-01-15T11:26:52.709Z - info: Elaborazione Lolmasters: Twisted Fate
2017-01-15T11:26:52.756Z - info: Elaborazione Champion.gg: Bard
2017-01-15T11:26:52.928Z - info: Elaborazione Lolmasters: Tryndamere
2017-01-15T11:26:53.155Z - info: Elaborazione Champion.gg: Blitzcrank
2017-01-15T11:26:53.186Z - info: Elaborazione Champion.gg: Brand
2017-01-15T11:26:53.190Z - info: Elaborazione Lolmasters: Trundle
2017-01-15T11:26:53.303Z - info: Elaborazione Champion.gg: Braum
2017-01-15T11:26:53.308Z - info: Elaborazione Lolmasters: Tristana
2017-01-15T11:26:53.377Z - info: Elaborazione Lolmasters: Thresh
2017-01-15T11:26:53.552Z - info: Elaborazione Lolmasters: Teemo
2017-01-15T11:26:53.641Z - info: Elaborazione Lolmasters: Taric
2017-01-15T11:26:53.855Z - info: Elaborazione Lolmasters: Talon
2017-01-15T11:26:53.923Z - info: Elaborazione Lolmasters: Taliyah
2017-01-15T11:26:54.005Z - info: Elaborazione Champion.gg: Caitlyn
2017-01-15T11:26:54.154Z - info: Elaborazione Champion.gg: Camille
2017-01-15T11:26:54.168Z - info: Elaborazione Lolmasters: Tahm Kench
2017-01-15T11:26:54.212Z - info: Elaborazione Lolmasters: Syndra
2017-01-15T11:26:54.442Z - info: Elaborazione Lolmasters: Swain
2017-01-15T11:26:54.682Z - info: Elaborazione Champion.gg: Cassiopeia
2017-01-15T11:26:54.719Z - info: Elaborazione Lolmasters: Soraka
2017-01-15T11:26:54.805Z - info: Elaborazione Champion.gg: Cho'Gath
2017-01-15T11:26:54.931Z - info: Elaborazione Lolmasters: Sona
2017-01-15T11:26:55.199Z - info: Elaborazione Lolmasters: Skarner
2017-01-15T11:26:55.319Z - info: Elaborazione Lolmasters: Sivir
2017-01-15T11:26:55.401Z - info: Elaborazione Champion.gg: Corki
2017-01-15T11:26:55.447Z - info: Elaborazione Lolmasters: Sion
2017-01-15T11:26:55.555Z - info: Elaborazione Lolmasters: Singed
2017-01-15T11:26:55.638Z - info: Elaborazione Lolmasters: Shyvana
2017-01-15T11:26:55.913Z - info: Elaborazione Lolmasters: Shen
2017-01-15T11:26:56.205Z - info: Elaborazione Champion.gg: Darius
2017-01-15T11:26:56.223Z - info: Elaborazione Lolmasters: Shaco
2017-01-15T11:26:56.437Z - info: Elaborazione Lolmasters: Sejuani
2017-01-15T11:26:56.572Z - info: Elaborazione Champion.gg: Diana
2017-01-15T11:26:56.736Z - info: Elaborazione Lolmasters: Ryze
2017-01-15T11:26:56.929Z - info: Elaborazione Champion.gg: Dr. Mundo
2017-01-15T11:26:56.940Z - info: Elaborazione Lolmasters: Rumble
2017-01-15T11:26:57.008Z - info: Elaborazione Champion.gg: Draven
2017-01-15T11:26:57.024Z - info: Elaborazione Lolmasters: Riven
2017-01-15T11:26:57.175Z - info: Elaborazione Lolmasters: Rengar
2017-01-15T11:26:57.266Z - info: Elaborazione Lolmasters: Renekton
2017-01-15T11:26:57.523Z - info: Elaborazione Lolmasters: Rek'Sai
2017-01-15T11:26:57.803Z - info: Elaborazione Champion.gg: Ekko
2017-01-15T11:26:57.805Z - info: Elaborazione Lolmasters: Rammus
2017-01-15T11:26:58.033Z - info: Elaborazione Champion.gg: Elise
2017-01-15T11:26:58.037Z - info: Elaborazione Lolmasters: Quinn
2017-01-15T11:26:58.256Z - info: Elaborazione Lolmasters: Poppy
2017-01-15T11:26:58.501Z - info: Elaborazione Lolmasters: Pantheon
2017-01-15T11:26:58.582Z - info: Elaborazione Champion.gg: Evelynn
2017-01-15T11:26:58.663Z - info: Elaborazione Champion.gg: Ezreal
2017-01-15T11:26:58.720Z - info: Elaborazione Lolmasters: Orianna
2017-01-15T11:26:59.035Z - info: Elaborazione Lolmasters: Olaf
2017-01-15T11:26:59.605Z - info: Elaborazione Champion.gg: Fiddlesticks
2017-01-15T11:26:59.627Z - info: Elaborazione Champion.gg: Fiora
2017-01-15T11:26:59.682Z - info: Elaborazione Champion.gg: Fizz
2017-01-15T11:27:00.310Z - info: Elaborazione Champion.gg: Galio
2017-01-15T11:27:00.386Z - info: Elaborazione Lolmasters: Nunu
2017-01-15T11:27:00.462Z - info: Elaborazione Lolmasters: Nocturne
2017-01-15T11:27:01.161Z - info: Elaborazione Champion.gg: Gangplank
2017-01-15T11:27:01.277Z - info: Elaborazione Lolmasters: Nidalee
2017-01-15T11:27:01.487Z - info: Elaborazione Champion.gg: Garen
2017-01-15T11:27:01.547Z - info: Elaborazione Lolmasters: Nautilus
2017-01-15T11:27:01.774Z - info: Elaborazione Lolmasters: Nasus
2017-01-15T11:27:01.866Z - info: Elaborazione Lolmasters: Nami
2017-01-15T11:27:02.009Z - info: Elaborazione Lolmasters: Morgana
2017-01-15T11:27:02.086Z - info: Elaborazione Champion.gg: Gnar
2017-01-15T11:27:02.110Z - info: Elaborazione Lolmasters: Mordekaiser
2017-01-15T11:27:02.191Z - info: Elaborazione Lolmasters: Wukong
2017-01-15T11:27:02.366Z - info: Elaborazione Lolmasters: Miss Fortune
2017-01-15T11:27:02.386Z - info: Elaborazione Champion.gg: Gragas
2017-01-15T11:27:02.464Z - info: Elaborazione Lolmasters: Master Yi
2017-01-15T11:27:02.647Z - info: Elaborazione Lolmasters: Maokai
2017-01-15T11:27:02.715Z - info: Elaborazione Champion.gg: Graves
2017-01-15T11:27:02.746Z - info: Elaborazione Lolmasters: Malzahar
2017-01-15T11:27:02.826Z - info: Elaborazione Champion.gg: Hecarim
2017-01-15T11:27:02.881Z - info: Elaborazione Lolmasters: Malphite
2017-01-15T11:27:02.977Z - info: Elaborazione Lolmasters: Lux
2017-01-15T11:27:03.158Z - info: Elaborazione Champion.gg: Heimerdinger
2017-01-15T11:27:03.167Z - info: Elaborazione Lolmasters: Lulu
2017-01-15T11:27:03.244Z - info: Elaborazione Lolmasters: Lucian
2017-01-15T11:27:03.453Z - info: Elaborazione Lolmasters: Lissandra
2017-01-15T11:27:03.538Z - info: Elaborazione Lolmasters: Leona
2017-01-15T11:27:03.618Z - info: Elaborazione Champion.gg: Illaoi
2017-01-15T11:27:03.691Z - info: Elaborazione Lolmasters: Lee Sin
2017-01-15T11:27:03.768Z - info: Elaborazione Lolmasters: LeBlanc
2017-01-15T11:27:03.937Z - info: Elaborazione Lolmasters: Kog'Maw
2017-01-15T11:27:04.026Z - info: Elaborazione Lolmasters: Kled
2017-01-15T11:27:04.201Z - info: Elaborazione Champion.gg: Irelia
2017-01-15T11:27:04.209Z - info: Elaborazione Lolmasters: Kindred
2017-01-15T11:27:04.291Z - info: Elaborazione Lolmasters: Kha'Zix
2017-01-15T11:27:04.360Z - info: Elaborazione Champion.gg: Ivern
2017-01-15T11:27:04.436Z - info: Elaborazione Lolmasters: Kennen
2017-01-15T11:27:04.582Z - info: Elaborazione Lolmasters: Kayle
2017-01-15T11:27:04.618Z - info: Elaborazione Champion.gg: Janna
2017-01-15T11:27:04.665Z - info: Elaborazione Lolmasters: Katarina
2017-01-15T11:27:04.852Z - info: Elaborazione Lolmasters: Kassadin
2017-01-15T11:27:04.939Z - info: Elaborazione Champion.gg: Jarvan IV
2017-01-15T11:27:04.943Z - info: Elaborazione Lolmasters: Karthus
2017-01-15T11:27:05.151Z - info: Elaborazione Lolmasters: Karma
2017-01-15T11:27:05.178Z - info: Elaborazione Lolmasters: Kalista
2017-01-15T11:27:05.444Z - info: Elaborazione Lolmasters: Jinx
2017-01-15T11:27:05.559Z - info: Elaborazione Champion.gg: Jax
2017-01-15T11:27:05.656Z - info: Elaborazione Lolmasters: Jhin
2017-01-15T11:27:05.901Z - info: Elaborazione Champion.gg: Jayce
2017-01-15T11:27:05.915Z - info: Elaborazione Lolmasters: Jayce
2017-01-15T11:27:06.127Z - info: Elaborazione Lolmasters: Jax
2017-01-15T11:27:06.187Z - info: Elaborazione Lolmasters: Jarvan IV
2017-01-15T11:27:06.341Z - info: Elaborazione Champion.gg: Jhin
2017-01-15T11:27:06.373Z - info: Elaborazione Lolmasters: Janna
2017-01-15T11:27:06.517Z - info: Elaborazione Lolmasters: Ivern
2017-01-15T11:27:06.608Z - info: Elaborazione Lolmasters: Irelia
2017-01-15T11:27:06.761Z - info: Elaborazione Lolmasters: Illaoi
2017-01-15T11:27:06.856Z - info: Elaborazione Lolmasters: Heimerdinger
2017-01-15T11:27:07.067Z - info: Elaborazione Champion.gg: Jinx
2017-01-15T11:27:07.072Z - info: Elaborazione Lolmasters: Hecarim
2017-01-15T11:27:07.153Z - info: Elaborazione Champion.gg: Kalista
2017-01-15T11:27:07.157Z - info: Elaborazione Lolmasters: Graves
2017-01-15T11:27:07.284Z - info: Elaborazione Lolmasters: Gragas
2017-01-15T11:27:07.413Z - info: Elaborazione Champion.gg: Karma
2017-01-15T11:27:07.429Z - info: Elaborazione Lolmasters: Gnar
2017-01-15T11:27:07.552Z - info: Elaborazione Lolmasters: Garen
2017-01-15T11:27:07.708Z - info: Elaborazione Lolmasters: Gangplank
2017-01-15T11:27:07.840Z - info: Elaborazione Champion.gg: Karthus
2017-01-15T11:27:07.850Z - info: Elaborazione Lolmasters: Galio
2017-01-15T11:27:07.941Z - info: Elaborazione Champion.gg: Kassadin
2017-01-15T11:27:07.961Z - info: Elaborazione Lolmasters: Fizz
2017-01-15T11:27:08.130Z - info: Elaborazione Lolmasters: Fiora
2017-01-15T11:27:08.213Z - info: Elaborazione Lolmasters: Fiddlesticks
2017-01-15T11:27:08.391Z - info: Elaborazione Lolmasters: Ezreal
2017-01-15T11:27:08.498Z - info: Elaborazione Lolmasters: Evelynn
2017-01-15T11:27:08.666Z - info: Elaborazione Lolmasters: Elise
2017-01-15T11:27:08.713Z - info: Elaborazione Champion.gg: Katarina
2017-01-15T11:27:08.721Z - info: Elaborazione Lolmasters: Ekko
2017-01-15T11:27:08.901Z - info: Elaborazione Champion.gg: Kayle
2017-01-15T11:27:08.905Z - info: Elaborazione Lolmasters: Draven
2017-01-15T11:27:08.957Z - info: Elaborazione Lolmasters: Dr. Mundo
2017-01-15T11:27:09.153Z - info: Elaborazione Lolmasters: Diana
2017-01-15T11:27:09.210Z - info: Elaborazione Lolmasters: Darius
2017-01-15T11:27:09.294Z - info: Elaborazione Champion.gg: Kennen
2017-01-15T11:27:09.427Z - info: Elaborazione Lolmasters: Corki
2017-01-15T11:27:09.461Z - info: Elaborazione Lolmasters: Cho'Gath
2017-01-15T11:27:09.630Z - info: Elaborazione Champion.gg: Kha'Zix
2017-01-15T11:27:09.666Z - info: Elaborazione Lolmasters: Cassiopeia
2017-01-15T11:27:09.798Z - info: Elaborazione Lolmasters: Camille
2017-01-15T11:27:10.121Z - info: Elaborazione Lolmasters: Caitlyn
2017-01-15T11:27:10.624Z - info: Elaborazione Lolmasters: Braum
2017-01-15T11:27:10.701Z - info: Elaborazione Champion.gg: Kindred
2017-01-15T11:27:10.768Z - info: Elaborazione Champion.gg: Kled
2017-01-15T11:27:10.873Z - info: Elaborazione Lolmasters: Brand
2017-01-15T11:27:11.104Z - info: Elaborazione Champion.gg: Kog'Maw
2017-01-15T11:27:11.113Z - info: Elaborazione Lolmasters: Blitzcrank
2017-01-15T11:27:11.360Z - info: Elaborazione Lolmasters: Bard
2017-01-15T11:27:11.429Z - info: Elaborazione Champion.gg: LeBlanc
2017-01-15T11:27:11.505Z - info: Elaborazione Champion.gg: Lee Sin
2017-01-15T11:27:11.509Z - info: Elaborazione Lolmasters: Azir
2017-01-15T11:27:11.586Z - info: Elaborazione Lolmasters: Aurelion Sol
2017-01-15T11:27:11.765Z - info: Elaborazione Lolmasters: Ashe
2017-01-15T11:27:11.901Z - info: Elaborazione Lolmasters: Annie
2017-01-15T11:27:12.026Z - info: Elaborazione Lolmasters: Anivia
2017-01-15T11:27:12.208Z - info: Elaborazione Champion.gg: Leona
2017-01-15T11:27:12.214Z - info: Elaborazione Lolmasters: Amumu
2017-01-15T11:27:12.304Z - info: Elaborazione Champion.gg: Lissandra
2017-01-15T11:27:12.311Z - info: Elaborazione Lolmasters: Alistar
2017-01-15T11:27:12.478Z - info: Elaborazione Champion.gg: Lucian
2017-01-15T11:27:12.514Z - info: Elaborazione Lolmasters: Akali
2017-01-15T11:27:13.046Z - info: Elaborazione Champion.gg: Lulu
2017-01-15T11:27:13.282Z - info: Elaborazione Champion.gg: Lux
2017-01-15T11:27:13.762Z - info: Elaborazione Champion.gg: Malphite
2017-01-15T11:27:13.801Z - info: Elaborazione Champion.gg: Malzahar
2017-01-15T11:27:14.508Z - info: Elaborazione Champion.gg: Maokai
2017-01-15T11:27:14.858Z - info: Elaborazione Champion.gg: Master Yi
2017-01-15T11:27:15.199Z - info: Elaborazione Champion.gg: Miss Fortune
2017-01-15T11:27:15.513Z - info: Elaborazione Champion.gg: Wukong
2017-01-15T11:27:15.785Z - info: Elaborazione Champion.gg: Mordekaiser
2017-01-15T11:27:16.194Z - info: Elaborazione Champion.gg: Morgana
2017-01-15T11:27:17.039Z - info: Elaborazione Champion.gg: Nami
2017-01-15T11:27:17.510Z - info: Elaborazione Champion.gg: Nasus
2017-01-15T11:27:17.843Z - info: Elaborazione Champion.gg: Nautilus
2017-01-15T11:27:17.872Z - info: Elaborazione Champion.gg: Nidalee
2017-01-15T11:27:18.210Z - info: Elaborazione Champion.gg: Nocturne
2017-01-15T11:27:18.604Z - info: Elaborazione Champion.gg: Nunu
2017-01-15T11:27:18.941Z - info: Elaborazione Champion.gg: Olaf
2017-01-15T11:27:19.256Z - info: Elaborazione Champion.gg: Orianna
2017-01-15T11:27:19.850Z - info: Elaborazione Champion.gg: Pantheon
2017-01-15T11:27:19.905Z - info: Elaborazione Champion.gg: Poppy
2017-01-15T11:27:20.433Z - info: Elaborazione Champion.gg: Quinn
2017-01-15T11:27:21.343Z - info: Elaborazione Champion.gg: Rammus
2017-01-15T11:27:21.436Z - info: Elaborazione Champion.gg: Rek'Sai
2017-01-15T11:27:22.005Z - info: Elaborazione Champion.gg: Renekton
2017-01-15T11:27:22.347Z - info: Elaborazione Champion.gg: Rengar
2017-01-15T11:27:22.663Z - info: Elaborazione Champion.gg: Riven
2017-01-15T11:27:23.048Z - info: Elaborazione Champion.gg: Rumble
2017-01-15T11:27:23.399Z - info: Elaborazione Champion.gg: Ryze
2017-01-15T11:27:23.792Z - info: Elaborazione Champion.gg: Sejuani
2017-01-15T11:27:24.566Z - info: Elaborazione Champion.gg: Shaco
2017-01-15T11:27:24.668Z - info: Elaborazione Champion.gg: Shen
2017-01-15T11:27:25.168Z - info: Elaborazione Champion.gg: Shyvana
2017-01-15T11:27:26.058Z - info: Elaborazione Champion.gg: Singed
2017-01-15T11:27:26.080Z - info: Elaborazione Champion.gg: Sion
2017-01-15T11:27:26.121Z - info: Elaborazione Champion.gg: Sivir
2017-01-15T11:27:26.739Z - info: Elaborazione Champion.gg: Skarner
2017-01-15T11:27:26.850Z - info: Elaborazione Champion.gg: Sona
2017-01-15T11:27:27.504Z - info: Elaborazione Champion.gg: Soraka
2017-01-15T11:27:27.526Z - info: Elaborazione Champion.gg: Swain
2017-01-15T11:27:27.647Z - info: Elaborazione Champion.gg: Syndra
2017-01-15T11:27:28.260Z - info: Elaborazione Champion.gg: Tahm Kench
2017-01-15T11:27:28.402Z - info: Elaborazione Champion.gg: Taliyah
2017-01-15T11:27:28.915Z - info: Elaborazione Champion.gg: Talon
2017-01-15T11:27:29.692Z - info: Elaborazione Champion.gg: Taric
2017-01-15T11:27:29.746Z - info: Elaborazione Champion.gg: Teemo
2017-01-15T11:27:30.644Z - info: Elaborazione Champion.gg: Thresh
2017-01-15T11:27:30.661Z - info: Elaborazione Champion.gg: Tristana
2017-01-15T11:27:30.725Z - info: Elaborazione Champion.gg: Trundle
2017-01-15T11:27:31.392Z - info: Elaborazione Champion.gg: Tryndamere
2017-01-15T11:27:31.418Z - info: Elaborazione Champion.gg: Twisted Fate
2017-01-15T11:27:32.147Z - info: Elaborazione Champion.gg: Twitch
2017-01-15T11:27:32.231Z - info: Elaborazione Champion.gg: Udyr
2017-01-15T11:27:32.962Z - info: Elaborazione Champion.gg: Urgot
2017-01-15T11:27:32.977Z - info: Elaborazione Champion.gg: Varus
2017-01-15T11:27:33.701Z - info: Elaborazione Champion.gg: Vayne
2017-01-15T11:27:34.340Z - info: Elaborazione Champion.gg: Veigar
2017-01-15T11:27:34.440Z - info: Elaborazione Champion.gg: Vel'Koz
2017-01-15T11:27:34.460Z - info: Elaborazione Champion.gg: Vi
2017-01-15T11:27:35.003Z - info: Elaborazione Champion.gg: Viktor
2017-01-15T11:27:35.228Z - info: Elaborazione Champion.gg: Vladimir
2017-01-15T11:27:35.634Z - info: Elaborazione Champion.gg: Volibear
2017-01-15T11:27:35.984Z - info: Elaborazione Champion.gg: Warwick
2017-01-15T11:27:36.647Z - info: Elaborazione Champion.gg: Xerath
2017-01-15T11:27:37.076Z - info: Elaborazione Champion.gg: Xin Zhao
2017-01-15T11:27:37.275Z - info: Elaborazione Champion.gg: Yasuo
2017-01-15T11:27:37.372Z - info: Elaborazione Champion.gg: Yorick
2017-01-15T11:27:38.101Z - info: Elaborazione Champion.gg: Zac
2017-01-15T11:27:38.383Z - info: Elaborazione Champion.gg: Zed
2017-01-15T11:27:38.952Z - info: Sto eliminando le vecchie build
2017-01-15T11:27:39.490Z - warn:  Error: UNKNOWN: unknown error, mkdir 'D:\Config\Champions\Thresh\Recommended'
    at Error (native)
2017-01-15T11:27:39.493Z - error:  FileWriteError: Failed to write item set json file
    at fs.mkdirsAsync.catch.then.catch.err (C:\Users\Simone\AppData\Local\Championify\app-2.0.1\resources\app.asar\js\championify.js:161:13)
    at tryCatcher (C:\Users\Simone\AppData\Local\Championify\app-2.0.1\resources\app.asar\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Simone\AppData\Local\Championify\app-2.0.1\resources\app.asar\node_modules\bluebird\js\release\promise.js:510:31)
    at Promise._settlePromise (C:\Users\Simone\AppData\Local\Championify\app-2.0.1\resources\app.asar\node_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (C:\Users\Simone\AppData\Local\Championify\app-2.0.1\resources\app.asar\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (C:\Users\Simone\AppData\Local\Championify\app-2.0.1\resources\app.asar\node_modules\bluebird\js\release\promise.js:687:18)
    at Async._drainQueue (C:\Users\Simone\AppData\Local\Championify\app-2.0.1\resources\app.asar\node_modules\bluebird\js\release\async.js:138:16)
    at Async._drainQueues (C:\Users\Simone\AppData\Local\Championify\app-2.0.1\resources\app.asar\node_modules\bluebird\js\release\async.js:148:10)
    at Async.drainQueues (C:\Users\Simone\AppData\Local\Championify\app-2.0.1\resources\app.asar\node_modules\bluebird\js\release\async.js:17:14)
Cause: Error: UNKNOWN: unknown error, open 'D:\Config\Champions\Thresh\Recommended\CIFY_Thresh_lolmasters_Support.json'
    at Error (native)

**Comment by dustinblackman** [comment]
@bloodygun Tried running as admin? Championify can't create a folder in that directory by something on your system preventing it.

**Comment by matthewswallace** [comment]
I'm having the same issue but on macOS. I tried chmod 777 on the file and I also tried sudo open /Application/Championify.app and neither worked.

**Comment by dustinblackman** [comment]
@matthewswallace macOS shouldn't that that issue at all as all applications should have access to `~/Library/Application Support/`. That sounds like something on your system specifically.

**Comment by Reythomas** [comment]
Excuse me I have the same problem of Json if they could help me would be great, and try everything to eliminate Antivirus

**Comment by Reythomas** [comment]
![image](https://user-images.githubusercontent.com/30163722/28193592-5b140472-6814-11e7-9d60-bd344b701472.png)

**Comment by dustinblackman** [comment]
@Reythomas Your issue is not related. https://github.com/dustinblackman/Championify/issues/243#issuecomment-269243071

**Comment by dustinblackman** [comment]
Stale, closing.
