### ISSUE TITLE
"Can't get champs" error

### ISSUE THREAD

**Issue by sleepyapples** [dustinblackman/Championify#374]
_Config and file locations:_
_- Log: 
{"level":"info","message":"Version: 2.1.3","timestamp":"2017-12-07T07:41:21.537Z"}
{"level":"info","message":"Checking for updates","timestamp":"2017-12-07T07:41:23.849Z"}
{"level":"info","message":"No updates found","timestamp":"2017-12-07T07:41:24.714Z"}
{"level":"info","message":"Locale: en","timestamp":"2017-12-07T07:43:45.758Z"}
{"level":"info","message":"Saved preference file to C:\\Users\\j\\AppData\\Roaming\\Championify\\prefs.json","timestamp":"2017-12-07T07:43:45.804Z"}
{"level":"info","message":"Getting LoL Version","timestamp":"2017-12-07T07:43:45.851Z"}
{"level":"info","message":"Downloading Champs from Riot","timestamp":"2017-12-07T07:43:45.908Z"}
{"message":"Can't get Champs","stack":"RequestError: Can't get Champs\n    at then.tap.data (C:\\Users\\j\\AppData\\Local\\Championify\\app-2.1.3\\resources\\app.asar\\js\\championify.js:100:22)\n    at PassThroughHandlerContext.finallyHandler (C:\\Users\\j\\AppData\\Local\\Championify\\app-2.1.3\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\finally.js:56:23)\n    at PassThroughHandlerContext.tryCatcher (C:\\Users\\j\\AppData\\Local\\Championify\\app-2.1.3\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\util.js:16:23)\n    at Promise._settlePromiseFromHandler (C:\\Users\\j\\AppData\\Local\\Championify\\app-2.1.3\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:510:31)\n    at Promise._settlePromise (C:\\Users\\j\\AppData\\Local\\Championify\\app-2.1.3\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:567:18)\n    at Promise._settlePromise0 (C:\\Users\\j\\AppData\\Local\\Championify\\app-2.1.3\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:612:10)\n    at Promise._settlePromises (C:\\Users\\j\\AppData\\Local\\Championify\\app-2.1.3\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:691:18)\n    at Async._drainQueue (C:\\Users\\j\\AppData\\Local\\Championify\\app-2.1.3\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\async.js:138:16)\n    at Async._drainQueues (C:\\Users\\j\\AppData\\Local\\Championify\\app-2.1.3\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\async.js:148:10)\n    at Async.drainQueues (C:\\Users\\j\\AppData\\Local\\Championify\\app-2.1.3\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\async.js:17:14)\n    at process._tickCallback (internal/process/next_tick.js:103:7)","code":"Can't get Champs","type":"RequestError","ua":"win32 6.3.9600","locale":"en","level":"error","timestamp":"2017-12-07T07:43:45.953Z"}_
_- Config: 
{
  "prefs_version": "2.1.3",
  "locale": "en",
  "install_path": "C:\\Riot Games\\PBE",
  "champ_path": "Config/Champions/",
  "local_is_version": "7.21",
  "options": {
    "splititems": false,
    "skillsformat": true,
    "consumables": true,
    "consumables_position": "end",
    "trinkets": true,
    "trinkets_position": "end",
    "locksr": false,
    "sr_source": [
      "championgg",
      "lolalytics",
      "opgg"
    ],
    "dontdeleteold": false,
    "aram": true
  }
}_

__What operating system: Windows 8.1__
__What version of Championify: 2.1.3__
__What distribution of the league client are you using (NA, EUW, KR, Garena, ect)?: 
PBE & Garena SG/MY__

__Please explain the issue you're encountering: 
For both PBE & Garena, trying to use Championify results in the same "can't get champs" error message. This happens regardless of what preferences (e.g. sources, whether to download ARAM sets, etc) are chosen. Error occurs 100% of the time since a few weeks ago (lol patch 7.21 according to Championify), without any changes on my end.__
__Screenshots: https://imgur.com/a/bX9dk__

__Things I've tried that didn't work:
1) uninstalling and reinstalling Championify, then running with administrator + firewall permissions
2) uninstalling and reinstalling PBE & Garena
3) changing Championify preferences
4) manually editing Champions folder of PBE/Garena to include and empty subfolder for Zoe__

__Additional issue encountered:
After reinstalling Garena client, file location changed to C:\Garena\Games\32771\Game without me changing any of the default installation settings. Although this folder does contain lol.exe, Championify doesn't seem to recognize it. Not sure if this would have prevented Championify from working in the end, because of the above "Can't get champs" error happening first.__

Thank you for making such a useful app like Championify :)
---

**Comment by dustinblackman** [comment]
Seems like you're having issue connecting to the Riot's champions endpoint, even though you didn't have a problem connecting to the versions endpoint.

What happens if you open the following link in a browser, does it load? If it does, could out attempt running Championify again, please? http://ddragon.leagueoflegends.com/cdn/7.24.1/data/en_US/champion.json

**Comment by sleepyapples** [comment]
The link loaded, but Championify seemed to have the same issue. Just in case, this is the new log: {"level":"info","message":"Version: 2.1.3","timestamp":"2017-12-09T16:30:45.951Z"}
{"level":"info","message":"Checking for updates","timestamp":"2017-12-09T16:30:47.637Z"}
{"level":"info","message":"No updates found","timestamp":"2017-12-09T16:30:49.988Z"}
{"level":"info","message":"Locale: en","timestamp":"2017-12-09T16:30:52.607Z"}
{"level":"info","message":"Saved preference file to C:\\Users\\j\\AppData\\Roaming\\Championify\\prefs.json","timestamp":"2017-12-09T16:30:52.625Z"}
{"level":"info","message":"Getting LoL Version","timestamp":"2017-12-09T16:30:52.637Z"}
{"level":"info","message":"Downloading Champs from Riot","timestamp":"2017-12-09T16:30:52.764Z"}
{"message":"Can't get Champs","stack":"RequestError: Can't get Champs\n    at then.tap.data (C:\\Users\\j\\AppData\\Local\\Championify\\app-2.1.3\\resources\\app.asar\\js\\championify.js:100:22)\n    at PassThroughHandlerContext.finallyHandler (C:\\Users\\j\\AppData\\Local\\Championify\\app-2.1.3\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\finally.js:56:23)\n    at PassThroughHandlerContext.tryCatcher (C:\\Users\\j\\AppData\\Local\\Championify\\app-2.1.3\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\util.js:16:23)\n    at Promise._settlePromiseFromHandler (C:\\Users\\j\\AppData\\Local\\Championify\\app-2.1.3\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:510:31)\n    at Promise._settlePromise (C:\\Users\\j\\AppData\\Local\\Championify\\app-2.1.3\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:567:18)\n    at Promise._settlePromise0 (C:\\Users\\j\\AppData\\Local\\Championify\\app-2.1.3\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:612:10)\n    at Promise._settlePromises (C:\\Users\\j\\AppData\\Local\\Championify\\app-2.1.3\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:691:18)\n    at Async._drainQueue (C:\\Users\\j\\AppData\\Local\\Championify\\app-2.1.3\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\async.js:138:16)\n    at Async._drainQueues (C:\\Users\\j\\AppData\\Local\\Championify\\app-2.1.3\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\async.js:148:10)\n    at Async.drainQueues (C:\\Users\\j\\AppData\\Local\\Championify\\app-2.1.3\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\async.js:17:14)\n    at process._tickCallback (internal/process/next_tick.js:103:7)","code":"Can't get Champs","type":"RequestError","ua":"win32 6.3.9600","locale":"en","level":"error","timestamp":"2017-12-09T16:30:53.352Z"}

**Comment by hollowsxd** [comment]
just fyi the new update checks for lolex.exe which is in the 32771 folder

**Comment by Axedus** [comment]
Hi, so has there been any progress on this issue? I have also encountered the same problem and nothing seems to work. Thanks.

**Comment by sleepyapples** [comment]
Sadly no, I've even tried on another desktop (windows 10) and this error still came up. So, so far it's happened across different computers/league clients/clean installs of league and championify.

**Comment by Axedus** [comment]
Hi sleepyapples, I recently managed to get championify to work by using wifi from a friend's house. Not sure as to why somehow my own wifi seems to be blocking championify. Perhaps you could try this method?

**Comment by sleepyapples** [comment]
Oh thank you for the info axedus I'll try that when I have a chance.

**Comment by dustinblackman** [comment]
That to me sounds like something on your network is the issue if you used the same machine in two different places. Championify shouldn't be doing anything different then what a web browser is doing however.

**Comment by Syoongy** [comment]
Facing the same issue as well. Link has no issues but championify gives this log : 
`{"level":"info","message":"Version: 2.1.3","timestamp":"2018-01-04T15:09:19.605Z"}
{"level":"info","message":"Checking for updates","timestamp":"2018-01-04T15:09:21.209Z"}
{"level":"info","message":"No updates found","timestamp":"2018-01-04T15:09:22.028Z"}
{"level":"info","message":"Locale: en","timestamp":"2018-01-04T15:09:26.814Z"}
{"level":"info","message":"Saved preference file to C:\\Users\\Fan Syong Yue\\AppData\\Roaming\\Championify\\prefs.json","timestamp":"2018-01-04T15:09:26.834Z"}
{"level":"info","message":"Getting LoL Version","timestamp":"2018-01-04T15:09:27.198Z"}
{"level":"info","message":"Downloading Champs from Riot","timestamp":"2018-01-04T15:09:27.216Z"}
{"message":"Can't get Champs","stack":"RequestError: Can't get Champs\n    at then.tap.data (C:\\Users\\Fan Syong Yue\\AppData\\Local\\Championify\\app-2.1.3\\resources\\app.asar\\js\\championify.js:100:22)\n    at PassThroughHandlerContext.finallyHandler (C:\\Users\\Fan Syong Yue\\AppData\\Local\\Championify\\app-2.1.3\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\finally.js:56:23)\n    at PassThroughHandlerContext.tryCatcher (C:\\Users\\Fan Syong Yue\\AppData\\Local\\Championify\\app-2.1.3\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\util.js:16:23)\n    at Promise._settlePromiseFromHandler (C:\\Users\\Fan Syong Yue\\AppData\\Local\\Championify\\app-2.1.3\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:510:31)\n    at Promise._settlePromise (C:\\Users\\Fan Syong Yue\\AppData\\Local\\Championify\\app-2.1.3\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:567:18)\n    at Promise._settlePromise0 (C:\\Users\\Fan Syong Yue\\AppData\\Local\\Championify\\app-2.1.3\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:612:10)\n    at Promise._settlePromises (C:\\Users\\Fan Syong Yue\\AppData\\Local\\Championify\\app-2.1.3\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:691:18)\n    at Async._drainQueue (C:\\Users\\Fan Syong Yue\\AppData\\Local\\Championify\\app-2.1.3\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\async.js:138:16)\n    at Async._drainQueues (C:\\Users\\Fan Syong Yue\\AppData\\Local\\Championify\\app-2.1.3\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\async.js:148:10)\n    at Async.drainQueues (C:\\Users\\Fan Syong Yue\\AppData\\Local\\Championify\\app-2.1.3\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\async.js:17:14)\n    at process._tickCallback (internal/process/next_tick.js:103:7)","code":"Can't get Champs","type":"RequestError","ua":"win32 10.0.16299","locale":"en","level":"error","timestamp":"2018-01-04T15:09:27.588Z"}`

**Comment by sleepyapples** [comment]
Oh wow so just to corroborated what you guys have said, Championify now works for me too. I haven't had a chance to try another wifi network, but had to change my router's settings (changing channels, disabling band steering, rebooting then exclusively using 5.0GHz) for something else, and it just started working after that. Not sure if any/which of those steps was the fix, but it might be worth a try for anyone else with this problem.
