### ISSUE TITLE
String undefined

### ISSUE THREAD

**Issue by burningscarlet** [dustinblackman/Championify#375]
Config
[prefs.zip](https://github.com/dustinblackman/Championify/files/1545951/prefs.zip)

Windows 10
Version 2.1.3
Garena Malaysia
Issue: When I try to run the program I get path must be a string. Received undefined, My locale is set to Japanese, is that why?

Log:
{"level":"info","message":"Version: 2.1.3","timestamp":"2017-12-10T18:58:57.396Z"}
{"message":"Path must be a string. Received undefined","stack":"TypeError: Path must be a string. Received undefined\n    at assertPath (path.js:7:11)\n    at Object.basename (path.js:801:5)\n    at Object.checkInstallPath (C:\\Users\\panda\\AppData\\Local\\Championify\\app-2.1.3\\resources\\app.asar\\js\\path_manager.js:93:43)\n    at Preferences.set (C:\\Users\\panda\\AppData\\Local\\Championify\\app-2.1.3\\resources\\app.asar\\js\\preferences.js:111:28)\n    at _initSettings (C:\\Users\\panda\\AppData\\Local\\Championify\\app-2.1.3\\resources\\app.asar\\js\\view_manager.js:163:32)\n    at r.html.promise.then (C:\\Users\\panda\\AppData\\Local\\Championify\\app-2.1.3\\resources\\app.asar\\js\\view_manager.js:250:73)\n    at j (C:\\Users\\panda\\AppData\\Local\\Championify\\app-2.1.3\\resources\\app.asar\\node_modules\\jquery\\dist\\jquery.min.js:2:29948)\n    at k (C:\\Users\\panda\\AppData\\Local\\Championify\\app-2.1.3\\resources\\app.asar\\node_modules\\jquery\\dist\\jquery.min.js:2:30262)","level":"error","timestamp":"2017-12-10T18:58:58.526Z"}

**Comment by dustinblackman** [comment]
I'm not seeing the same error as you, but am seeing something else related to the Japanese locale. Try deleting your `prefs.json` and restarting as a temporary fix for now. I'll look deeper in to the issue.

**Comment by burningscarlet** [comment]
It works but now it won't let me select my game folder then I get the same error. Better than before though.

I think it has something to do with the \ symbol being replaced with the  ¥ symbol in Japanese. Or maybe that's just me
