### ISSUE TITLE
Can't figure out what was the issue, but here's the log

### ISSUE THREAD

**Issue by anasred123** [dustinblackman/Championify#399]
_Please fill in the following when reporting an issue/bug and remove this line. Please include all logs, configs, and
screenshots if possible._

_Config and file locations:_
_- Log: C:/Users/YOURNAME/AppData/Roaming/Championify/championify.log.txt_
_- Config: C:/Users/YOURNAME/AppData/Roaming/Championify/prefs.json_

__What operating system:__
Windows10
__What version of Championify:__
v2.1.5
__What distribution of the league client are you using (NA, EUW, KR, Garena, ect)?:__
EUNE
__Please explain the issue you're encountering:__
Cant say for sure, But it didn't even manage begin to download.
__Screenshots:__
__Logs:__
{"level":"info","message":"Version: 2.1.5","timestamp":"2018-05-03T09:55:22.973Z"}
{"level":"info","message":"Checking for updates","timestamp":"2018-05-03T09:55:24.890Z"}
{"level":"info","message":"No updates found","timestamp":"2018-05-03T09:55:27.148Z"}
{"level":"info","message":"Locale: en","timestamp":"2018-05-03T09:56:37.086Z"}
{"level":"info","message":"Saved preference file to C:\\Users\\technoob123\\AppData\\Roaming\\Championify\\prefs.json","timestamp":"2018-05-03T09:56:37.114Z"}
{"level":"info","message":"Getting LoL Version","timestamp":"2018-05-03T09:56:49.699Z"}
{"level":"info","message":"Downloading Champs from Riot","timestamp":"2018-05-03T09:56:50.459Z"}
{"message":"Error","stack":"RequestError: Error\n    at requester.then.catch.err (C:\\Users\\technoob123\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\js\\helpers\\request.js:156:18)\n    at tryCatcher (C:\\Users\\technoob123\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\util.js:16:23)\n    at Promise._settlePromiseFromHandler (C:\\Users\\technoob123\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:510:31)\n    at Promise._settlePromise (C:\\Users\\technoob123\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:567:18)\n    at Promise._settlePromise0 (C:\\Users\\technoob123\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:612:10)\n    at Promise._settlePromises (C:\\Users\\technoob123\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:687:18)\n    at Async._drainQueue (C:\\Users\\technoob123\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\async.js:138:16)\n    at Async._drainQueues (C:\\Users\\technoob123\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\async.js:148:10)\n    at Async.drainQueues (C:\\Users\\technoob123\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\async.js:17:14)\n    at process._tickCallback (internal/process/next_tick.js:103:7)","code":"Error","url":"http://ddragon.leagueoflegends.com/cdn/8.9.1/data/en_US/champion.json","body":{"cause":{"code":"ESOCKETTIMEDOUT","connect":false},"isOperational":true,"code":"ESOCKETTIMEDOUT","connect":false},"type":"RequestError","ua":"win32 10.0.16299","locale":"en","level":"error","timestamp":"2018-05-03T09:57:24.567Z"}

---

_Please fill in the following for feature requests:_

__Description of feature:__
__Mocks/screenshots of ideas:__

**Comment by dustinblackman** [comment]
Are you able to open this link in a browser? Cause something it preventing Championify from accessing it. http://ddragon.leagueoflegends.com/cdn/8.9.1/data/en_US/champion.json

**Comment by anasred123** [comment]
Hey dustin, thank you for making the time for my oddly issue. Am I supposed to see bunch of codes when i open the link.  
![untitled123](https://user-images.githubusercontent.com/38941429/39587391-f6d1c90e-4f2b-11e8-9bf9-c799e453b566.png)

**Comment by dustinblackman** [comment]
Yeah that's the correct output. Do you have a firewall/anti virus or such that's blocking it? That's the only possibility really. The error you posted in your log stats that it can't access the URL you opened in your browser, so I'm putting the blame on an AV.

**Comment by anasred123** [comment]
I have turned off the firewall or anti virus even I have put it app exception, And the problem kept persist. I think it have to do with the ISP currently I'm using. I'm using the Uni's internet.
