### ISSUE TITLE
Stuck at Downloading Champions 

### ISSUE THREAD

**Issue by GioGioKING** [dustinblackman/Championify#421]
{"level":"info","message":"Version: 2.1.5","timestamp":"2018-07-14T11:55:49.651Z"}
{"level":"info","message":"Checking for updates","timestamp":"2018-07-14T11:55:51.213Z"}
{"level":"info","message":"No updates found","timestamp":"2018-07-14T11:55:51.349Z"}
{"message":"Can't get Champion.gg version","stack":"RequestError: Can't get Champion.gg version\n    at then.catch.err (C:\\Users\\glaur\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\js\\sources\\championgg.js:110:11)\n    at tryCatcher (C:\\Users\\glaur\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\util.js:16:23)\n    at Promise._settlePromiseFromHandler (C:\\Users\\glaur\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:510:31)\n    at Promise._settlePromise (C:\\Users\\glaur\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:567:18)\n    at Promise._settlePromise0 (C:\\Users\\glaur\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:612:10)\n    at Promise._settlePromises (C:\\Users\\glaur\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:687:18)\n    at Async._drainQueue (C:\\Users\\glaur\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\async.js:138:16)\n    at Async._drainQueues (C:\\Users\\glaur\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\async.js:148:10)\n    at Async.drainQueues (C:\\Users\\glaur\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\async.js:17:14)\nCause: RequestError: Error\n    at requester.then.catch.err (C:\\Users\\glaur\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\js\\helpers\\request.js:156:18)\n    at tryCatcher (C:\\Users\\glaur\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\util.js:16:23)\n    at Promise._settlePromiseFromHandler (C:\\Users\\glaur\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:510:31)\n    at Promise._settlePromise (C:\\Users\\glaur\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:567:18)\n    at Promise._settlePromise0 (C:\\Users\\glaur\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:612:10)\n    at Promise._settlePromises (C:\\Users\\glaur\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:687:18)\n    at Async._drainQueue (C:\\Users\\glaur\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\async.js:138:16)\n    at Async._drainQueues (C:\\Users\\glaur\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\async.js:148:10)\n    at Async.drainQueues (C:\\Users\\glaur\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\async.js:17:14)","code":"Can't get Champion.gg version","type":"RequestError","ua":"win32 10.0.17134","locale":"en","cause":{"message":"Error","code":"Error","url":"http://champion.gg/faq/","body":{"cause":{"code":"ETIMEDOUT","connect":false},"isOperational":true,"code":"ETIMEDOUT","connect":false},"type":"RequestError","ua":"win32 10.0.17134","locale":"en"},"rootCause":{"message":"Error","code":"Error","url":"http://champion.gg/faq/","body":{"cause":{"code":"ETIMEDOUT","connect":false},"isOperational":true,"code":"ETIMEDOUT","connect":false},"type":"RequestError","ua":"win32 10.0.17134","locale":"en"},"ownStack":"RequestError: Can't get Champion.gg version\n    at then.catch.err (C:\\Users\\glaur\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\js\\sources\\championgg.js:110:11)\n    at tryCatcher (C:\\Users\\glaur\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\util.js:16:23)\n    at Promise._settlePromiseFromHandler (C:\\Users\\glaur\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:510:31)\n    at Promise._settlePromise (C:\\Users\\glaur\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:567:18)\n    at Promise._settlePromise0 (C:\\Users\\glaur\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:612:10)\n    at Promise._settlePromises (C:\\Users\\glaur\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:687:18)\n    at Async._drainQueue (C:\\Users\\glaur\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\async.js:138:16)\n    at Async._drainQueues (C:\\Users\\glaur\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\async.js:148:10)\n    at Async.drainQueues (C:\\Users\\glaur\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\async.js:17:14)","level":"warn","timestamp":"2018-07-14T11:56:21.212Z"}
{"message":"Error","stack":"RequestError: Error\n    at requester.then.catch.err (C:\\Users\\glaur\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\js\\helpers\\request.js:156:18)\n    at tryCatcher (C:\\Users\\glaur\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\util.js:16:23)\n    at Promise._settlePromiseFromHandler (C:\\Users\\glaur\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:510:31)\n    at Promise._settlePromise (C:\\Users\\glaur\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:567:18)\n    at Promise._settlePromise0 (C:\\Users\\glaur\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:612:10)\n    at Promise._settlePromises (C:\\Users\\glaur\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:687:18)\n    at Async._drainQueue (C:\\Users\\glaur\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\async.js:138:16)\n    at Async._drainQueues (C:\\Users\\glaur\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\async.js:148:10)\n    at Async.drainQueues (C:\\Users\\glaur\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\async.js:17:14)","code":"Error","url":"http://koreanbuilds.net/","body":{"cause":{"code":"ETIMEDOUT","connect":false},"isOperational":true,"code":"ETIMEDOUT","connect":false},"type":"RequestError","ua":"win32 10.0.17134","locale":"en","level":"warn","timestamp":"2018-07-14T11:56:21.213Z"}
{"message":"Error","stack":"RequestError: Error\n    at requester.then.catch.err (C:\\Users\\glaur\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\js\\helpers\\request.js:156:18)\n    at tryCatcher (C:\\Users\\glaur\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\util.js:16:23)\n    at Promise._settlePromiseFromHandler (C:\\Users\\glaur\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:510:31)\n    at Promise._settlePromise (C:\\Users\\glaur\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:567:18)\n    at Promise._settlePromise0 (C:\\Users\\glaur\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:612:10)\n    at Promise._settlePromises (C:\\Users\\glaur\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:687:18)\n    at Async._drainQueue (C:\\Users\\glaur\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\async.js:138:16)\n    at Async._drainQueues (C:\\Users\\glaur\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\async.js:148:10)\n    at Async.drainQueues (C:\\Users\\glaur\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\async.js:17:14)","code":"Error","url":"http://championify.lolalytics.com/data/1.0/ranked.json","body":{"cause":{"code":"ETIMEDOUT","connect":false},"isOperational":true,"code":"ETIMEDOUT","connect":false},"type":"RequestError","ua":"win32 10.0.17134","locale":"en","level":"warn","timestamp":"2018-07-14T11:56:21.214Z"}
{"message":"Error","stack":"RequestError: Error\n    at requester.then.catch.err (C:\\Users\\glaur\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\js\\helpers\\request.js:156:18)\n    at tryCatcher (C:\\Users\\glaur\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\util.js:16:23)\n    at Promise._settlePromiseFromHandler (C:\\Users\\glaur\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:510:31)\n    at Promise._settlePromise (C:\\Users\\glaur\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:567:18)\n    at Promise._settlePromise0 (C:\\Users\\glaur\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:612:10)\n    at Promise._settlePromises (C:\\Users\\glaur\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:687:18)\n    at Async._drainQueue (C:\\Users\\glaur\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\async.js:138:16)\n    at Async._drainQueues (C:\\Users\\glaur\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\async.js:148:10)\n    at Async.drainQueues (C:\\Users\\glaur\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\async.js:17:14)","code":"Error","url":"http://www.lolflavor.com/champions/Ahri/Recommended/Ahri_mid_scrape.json","body":{"cause":{"code":"ETIMEDOUT","connect":false},"isOperational":true,"code":"ETIMEDOUT","connect":false},"type":"RequestError","ua":"win32 10.0.17134","locale":"en","level":"warn","timestamp":"2018-07-14T11:56:21.215Z"}
{"message":"Error","stack":"RequestError: Error\n    at requester.then.catch.err (C:\\Users\\glaur\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\js\\helpers\\request.js:156:18)\n    at tryCatcher (C:\\Users\\glaur\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\util.js:16:23)\n    at Promise._settlePromiseFromHandler (C:\\Users\\glaur\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:510:31)\n    at Promise._settlePromise (C:\\Users\\glaur\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:567:18)\n    at Promise._settlePromise0 (C:\\Users\\glaur\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:612:10)\n    at Promise._settlePromises (C:\\Users\\glaur\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:687:18)\n    at Async._drainQueue (C:\\Users\\glaur\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\async.js:138:16)\n    at Async._drainQueues (C:\\Users\\glaur\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\async.js:148:10)\n    at Async.drainQueues (C:\\Users\\glaur\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\async.js:17:14)","code":"Error","url":"http://lolmasters.net/about","body":{"cause":{"code":"ETIMEDOUT","connect":false},"isOperational":true,"code":"ETIMEDOUT","connect":false},"type":"RequestError","ua":"win32 10.0.17134","locale":"en","level":"warn","timestamp":"2018-07-14T11:56:21.216Z"}
{"level":"info","message":"Locale: en","timestamp":"2018-07-14T11:56:30.297Z"}
{"level":"info","message":"Saved preference file to C:\\Users\\glaur\\AppData\\Roaming\\Championify\\prefs.json","timestamp":"2018-07-14T11:56:30.316Z"}
{"level":"info","message":"Getting LoL Version","timestamp":"2018-07-14T11:56:30.932Z"}
{"level":"info","message":"Downloading Champs from Riot","timestamp":"2018-07-14T11:56:31.162Z"}
{"message":"Error","stack":"RequestError: Error\n    at requester.then.catch.err (C:\\Users\\glaur\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\js\\helpers\\request.js:156:18)\n    at tryCatcher (C:\\Users\\glaur\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\util.js:16:23)\n    at Promise._settlePromiseFromHandler (C:\\Users\\glaur\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:510:31)\n    at Promise._settlePromise (C:\\Users\\glaur\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:567:18)\n    at Promise._settlePromise0 (C:\\Users\\glaur\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:612:10)\n    at Promise._settlePromises (C:\\Users\\glaur\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:687:18)\n    at Async._drainQueue (C:\\Users\\glaur\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\async.js:138:16)\n    at Async._drainQueues (C:\\Users\\glaur\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\async.js:148:10)\n    at Async.drainQueues (C:\\Users\\glaur\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\async.js:17:14)","code":"Error","url":"http://ddragon.leagueoflegends.com/cdn/8.13.1/data/en_US/champion.json","body":{"cause":{"code":"ETIMEDOUT","connect":false},"isOperational":true,"code":"ETIMEDOUT","connect":false},"type":"RequestError","ua":"win32 10.0.17134","locale":"en","level":"error","timestamp":"2018-07-14T11:57:01.174Z"}

**Comment by GioGioKING** [comment]
Ok i've fixed, just disable malwarebytes and it works again
