### ISSUE TITLE
Build error: "TypeError: Cannot promisify an API that has normal methods with 'Async'-suffix"

### ISSUE THREAD

**Issue by corylulu** [dustinblackman/Championify#429]
I was getting build errors when I initially pulled the project that read: 

```
> gulp postinstall
[20:35:58] Requiring external module babel-core/register
C:\projects\championify\node_modules\bluebird\js\release\promisify.js:54
                    throw new TypeError("Cannot promisify an API that has normal methods with '%s'-suffix\u000a\u000a    See http://goo.gl/MqrFmX\u000a"
                    ^
TypeError: Cannot promisify an API that has normal methods with 'Async'-suffix
    See http://goo.gl/MqrFmX
    at checkValid (C:\projects\championify\node_modules\bluebird\js\release\promisify.js:54:27)
    at promisifiableMethods (C:\projects\championify\node_modules\bluebird\js\release\promisify.js:77:5)
    at promisifyAll (C:\projects\championify\node_modules\bluebird\js\release\promisify.js:241:9)
    at Function.Promise.promisifyAll (C:\projects\championify\node_modules\bluebird\js\release\promisify.js:311:12)
    at Object.<anonymous> (C:/projects/championify/tasks/coverage.js:22:20)
    at Module._compile (module.js:570:32)
    at loader (C:\projects\championify\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (C:\projects\championify\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at requireDir (C:\projects\championify\node_modules\require-dir\index.js:116:33)
    at Object.<anonymous> (C:/projects/championify/gulpfile.babel.js:6:1)
    at Module._compile (module.js:570:32)
    at loader (C:\projects\championify\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (C:\projects\championify\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
```

I could not figure out how to resolve it, so I had literally just commented out the error check in the `bluebird` repository to make it build. Lol. 

The AppVeyor build does the same thing, so it's not just my environment. Not sure what the issue is with that.

**Comment by corylulu** [comment]
Fixed in #428
